---
# nakedBug blog configuration file
#
# Please change this config file before generating your asciidoc backend.
# There is no need to re-generate asciidoc backend if you change this config
# file, except for $blogtitle and $blogurl.

blogtitle: "Pingbo Wen's Blog"

# must add protocol before the url
blogroot: "http://202.201.0.164/blog"

# your posts location, each post should have a separated dir
# eg. 
# | --- {txtpath}
#       | --- catalog1
#             | --- firstpost
# 	          |     | --> firstpost.html
#             |     | --- css
#             |     | --- js
#             | --- secondpost
#                   | --> secondpost.html
#                   | --- ....
# related to blog root path
# the default posts location is article

# Specify the nav bar items' name icon, and related path
# Because using bootstrap in nakedBug, you can use some inherit icon, for
# details about those icons, visit
# http://getbootstrap.com/2.3.2/base-css.html#icons
nav_items: 
    Project: 
        icon: th
        url: "#"
    About me: 
        icon: user
        url: "#"
...
